dist: trusty
sudo: required
language: c++
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake libpng-dev libmikmod-dev libboost-all-dev

script: cmake -DCMAKE_BUILD_TYPE=Release . && make -j2 && make run_tests

compiler:
  - clang
  - gcc
